### ISSUE TITLE
Incorrect url behavior on model using Backbone Associations

### ISSUE THREAD

**Issue by dbryand** [backbone-paginator/backbone-pageable#101] opened 2013-07-25 17:44 UTC
I have a `ProjectAccesses` collection which extends `PageableCollection`. The collection model `ProjectAccess` implements relations via [Backbone Associations](http://dhruvaray.github.io/backbone-associations/). `ProjectAccess` has one `Invitation`.

```
  class Entities.ProjectAccess extends App.Entities.Model
    relations: [
      type: Backbone.One
      key: 'invitation'
      relatedModel: 'App.Entities.Invitation'
    ]

    urlRoot: ->
        "/api/projects/#{@get('project_id')}/accesses"

  class Entities.ProjectAccesses extends Backbone.PageableCollection
    model: Entities.ProjectAccess

  class Entities.Invitation extends App.Entities.Model
    urlRoot: ->
      "/api/invitations"
```

When I access an `Invitation` which was instantiated through the collection, it has an incorrect `url` set as an attribute which it has taken from the related `ProjectAccess`. It also does not have `url()` defined as it should.

```
Uncaught TypeError: Property 'url' of object #<Invitation> is not a function
```

When ProjectAccesses extends Backbone.Collection, everything works fine.

![screen shot 2013-07-25 at 10 48 42 am](https://f.cloud.github.com/assets/9218/857507/8212d1fe-f552-11e2-95c3-cb0db0ce7d94.png)

Thanks for looking at this.

**Comment by wyuenho** [comment] 2013-07-25 22:51
> When I access an Invitation which was instantiated through the collection

You mean calling PagebleCollection#create?

**Comment by dbryand** [comment] 2013-07-26 04:01
...by calling PageableCollection#fetch.

**Comment by bazineta** [comment] 2013-08-02 16:49
Having the same issue here.  Collection works fine, but PageableCollection replaces the model's url function with a string identical to that of the url of the collection.

**Comment by bazineta** [comment] 2013-08-02 21:26
However, upon testing with the master version of backbone.js instead of the 1.0.0 release, my issue seems to be resolved.

**Comment by wyuenho** [comment] 2013-08-14 17:12
@dbryand can you confirm that this issue is resolved with backbone master?

**Comment by joshgreco** [comment] 2013-09-06 00:07
I was having the same issue and can confirm that updating to the the master version of Backbone resolved the problem.

As an aside, thank you for Pageable. Its fantastic.

**Comment by wyuenho** [comment] 2013-09-06 05:05
Ok closing this.

**Closed as completed by wyuenho** 2013-09-06 05:05 UTC
Labels: bug

**Comment by dbryand** [comment] 2013-09-06 13:21
Also working for me--thank you!

**Comment by andrewdmoreno** [comment] 2013-09-12 21:42
Hi folks, also having the same problem - but in my attempt to point to master as suggested my app is broken due to what appears to be the options hash disappearing from this.options in my views. Wondering if that happened to any of you folks? As an FYI I am extending Marionette Layout/ItemViews (v 1.1.0). Wanted to check in with yall first before I pursue other avenues in the repositories of those projects.

**Comment by dbryand** [comment] 2013-09-12 23:07
I can't remember how I solved it, but I also had that deal with this.options breaking. I think it happened in cases where I had explicitly declared an `function initialize(options) {...}` but can't exactly remember. Will look when I have a chance.

**Comment by bazineta** [comment] 2013-09-12 23:16
As I recall, in master there are now only a handful of 'standard' options automatically added to a view, e.g., collection, model.  For your own, you add them to this yourself in intialize(options), where they are available in the option hash passed to initialize.  So there, for example, this.foo = options.foo should take care of your issue.

**Comment by smazurov** [comment] 2013-09-24 00:01
I think its poor form to close this because it doesn't happen in backbone/master instead of a stable versioned release. We all know backbone takes forever to do releases and thus we shouldn't force people to use non-versioned  libs as a fix for this bug.

Just my 2 cents.  For now, i added following workaround (in case anyone is hitting the same problem and unwilling to use `master` backbone):

``` javascript
Backbone.PageableCollection.extend({
  set: function(models, options) {
    options = options || {};
    delete options.url;
    Backbone.PageableCollection.prototype.set.call(this, models, options);
  }
}
```

This is untested beyond my application and I'm unsure if it would correctly work in a case where you rely on your collection to set the url.

**Comment by wyuenho** [comment] 2013-09-24 10:12
This is a side effect of https://github.com/documentcloud/backbone/issues/2416. pageable's test suite has already moved beyond backbone 1.0 and is using the master's test suite from 2 months ago. It's safer to just upgrade to backbone master. It has less regression, and better tested.

**Comment by smazurov** [comment] 2013-09-24 23:10
I agree with backbone and I see that you have been asking them to move along to get the versioned fix in, which is great and appreciated, it really comes down to the fact that backbone doesn't release often at all, and they need to fix it. Unfortunately there is a bunch of reasons for why I rather not switch to master, and at any rate my fix can easily be reverted later, so its not a huge deal. A suggestion I have is to at least mention where support and testing lies, indicating the broken functionality that is broken because backbone is basically slow to release.

Either way, I appreciate the response and the constant bugging on backbone proper to get version bumped.
