### ISSUE TITLE
url method not calling on save model

### ISSUE THREAD

**Issue by MikeVL** [backbone-paginator/backbone-pageable#70] opened 2013-04-10 20:08 UTC
i testing with two variants:

```
var PageableTerritories = Backbone.Collection.extend({
    model: Territory,
    url: function () {
        console.log(this);
        return "/api/market/offer"
    }
  });
```

On save model request: POST http://***/api/market/offer/14940171314
And console output two time. On fetch and save.
This is correct and work fine.

But with PageableCollection

```
var PageableTerritories = Backbone.PageableCollection.extend({
    model: Territory,
    url: function () {
        console.log(this);
        return "/api/market/offer"
    }
});
```

On save model request: POST http://***/api/market/offer
And console output only one time. Just on fetch.
This is not correct. On POST same url.

**Comment by wyuenho** [comment] 2013-04-11 04:13
Mmm, the collection's `url` seems to have overwritten the model's.

**Comment by MikeVL** [comment] 2013-04-11 06:59
This full code

```
var Territory = Backbone.Model.extend({
    defaults: {
        price: 0.00,
        quantity: 0.00,
        is_active: true
    },
    initialize: function () {
        this.on('change', function() { this.save(); });
    },
    parse: function (resp, options) {
        resp.price = parseFloat(resp.price);
        return resp;
    }
});

var PageableTerritories = Backbone.PageableCollection.extend({
    model: Territory,
    // url: "/api/market/offer",
    url: function () {
        console.log(this);
        return "/api/market/offer"
    },
    parse: function(resp) {
        return resp.results
    },
    parseState: function (resp, queryParams, state) {
        return { totalRecords: resp.count };
    },

    parseRecords: function (resp) {
        return resp.results
    }
});
```

**Comment by wyuenho** [comment] 2013-04-11 07:44
This looks like https://github.com/documentcloud/backbone/issues/2416 because `PageableCollection#fetch` sets `options.url` before calling `Collection#fetch`, and it overwrites Model#url.

**Comment by MikeVL** [comment] 2013-04-11 08:21
With Backbone version 0.9.10 works fine.

**Comment by wyuenho** [comment] 2013-04-11 08:28
Yep. It's supposed to work with 0.9.10. 1.0.0 broke this.

**Comment by lumicore-max** [comment] 2013-04-12 12:39
Are you able to fix this issue or we have to rollback backbone version?

**Comment by wyuenho** [comment] 2013-04-12 13:04
This issue is fixed in Backbone's master branch. I'll commit a workaround for this issue shortly. (Busy week)

**Comment by Integral** [comment] 2013-05-02 14:54
Well, I can confirm that if I have url: /api/check in my model and collection - all PUT and DELETE (made by model.destroy()) requests also addressed on /api/check, not /api/check/:id.

**Comment by throrin19** [comment] 2013-05-17 09:43
i confirm that and this error block my development. It's possible to fix that quickly? I can't use DELETE and UPDATE on my pagined models

**Comment by wyuenho** [comment] 2013-05-17 09:48
Please use Backbone master or downgrade to 0.9.10 for now. It turns out that there's no satisfactory work-around/fix for this problem.

**Comment by throrin19** [comment] 2013-05-17 10:03
I use the AMD backbone version in client side and they don't make master BackboneJS, just stable versions. And it's not possible at this moment to downgrade.

**Comment by wyuenho** [comment] 2013-05-17 10:57
You can shim backbone yourself without using a pre-made AMD-enabled backbone.

http://requirejs.org/docs/api.html#config-shim

**Comment by throrin19** [comment] 2013-05-17 13:41
thanks, it works on BackboneJS master ;)

**Closed as completed** 2013-07-20 16:00 UTC
Labels: bug, client mode, server mode, infinite mode

**Comment by kadkaz** [comment] 2013-07-30 06:25
workaround to use inside your model initialize method:
<code><pre>
initialize: function () {
        this.url = function () {
            return '/api/ship/' + this.get('id')
        }
    }
</pre>
</code>
